"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function AccountSettings() {
  const router=useRouter(); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/account/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:name})});const b=await r.json();if(!r.ok)throw Error(b.error);setMessage("Settings saved.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false)}}
  async function remove(){if(window.prompt("Type DELETE MY ACCOUNT to confirm")!=="DELETE MY ACCOUNT")return;setBusy(true);try{const r=await fetch("/api/account/delete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation:"DELETE MY ACCOUNT"})});const b=await r.json();if(!r.ok)throw Error(b.error);router.push("/");}catch(e){setMessage(e instanceof Error?e.message:"Unable to start deletion.");}finally{setBusy(false)}}
  return <main id="main" className="account-settings-page"><span className="eyebrow">ACCOUNT</span><h1>Account settings</h1><p>Keep your profile and notification choices up to date.</p><section className="settings-card"><label>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" maxLength={80}/></label><button className="button" disabled={busy||!name.trim()} onClick={save}>{busy?"Saving…":"Save changes"}</button>{message&&<p role="status">{message}</p>}</section><section className="settings-card danger-zone"><h2>Delete account</h2><p>Your identity will be deactivated. Financial records remain retained where required for accounting and support, and active VIP memberships are canceled.</p><button className="button button-secondary" disabled={busy} onClick={remove}>Request account deletion</button></section></main>;
}
