import { LegalPage } from "@/components/legal-page";
import { pageMetadata } from "@/lib/metadata";
export const metadata = pageMetadata(
  "Terms",
  "/terms",
  "Terms governing ReplyPass accounts, creator requests, payments and VIP memberships.",
  true,
);
export default function Page() {
  return (
    <LegalPage title="Terms of service" summary="These terms govern use of ReplyPass by fans and creators. You must be at least 18 and legally able to enter a contract. Creator-specific obligations also appear in the Creator Terms."
      sections={[
        {title:"1. The service",paragraphs:["ReplyPass is an online platform through which fans can request digital interactions from independent creators and buy recurring VIP access. The launch products are Guaranteed Reply, Voice Note, Photo Request and VIP. ReplyPass does not promise that a creator will accept a request.","Creators provide their own content and interactions. ReplyPass operates the platform and payment workflow; Stripe provides payment processing and connected-account services."]},
        {title:"2. Accounts",bullets:["Provide accurate information and keep credentials secure.","One person may not impersonate another, evade a suspension, scrape the service, or use another person’s payment method without permission.","We may request identity, age, fraud, tax, or business information and may suspend access while reviewing it.","You may request account deletion in Settings. Financial, safety, tax, dispute, and legal records may be retained where required."]},
        {title:"3. Paid requests and authorization",paragraphs:["The checkout shows the total price before confirmation. A paid request normally places an authorization on the fan’s payment method. It is not captured merely because the creator accepts.","For Guaranteed Reply, capture occurs when the creator sends the first qualifying reply. For Voice Note and Photo Request, capture occurs when validated media is privately stored, delivered, and the fan’s access entitlement is created. Opening the delivery is not required for capture."],bullets:["If the creator declines or the request expires without qualifying delivery, ReplyPass cancels the authorization. The bank controls how quickly a released hold disappears.","A creator’s later price change does not alter an existing authorized request.","Disabled products reject new purchases but do not erase transaction history."]},
        {title:"4. VIP memberships",paragraphs:["VIP is a recurring monthly subscription for the benefits displayed at checkout, such as private posts, exclusive updates, a badge or priority status. It does not include unlimited replies unless the checkout expressly says so.","The price accepted at subscription starts remains attached to that subscription unless the fan affirmatively accepts a new price. Creator price changes apply to new subscriptions. Fans can cancel through the available subscription-management flow; cancellation normally takes effect at the end of the paid billing period. Failed payment may suspend access."]},
        {title:"5. Cancellation, withdrawal and refunds",paragraphs:["Nothing in these terms limits mandatory consumer rights. Where applicable law gives a withdrawal right, the checkout must obtain any legally required express request for immediate performance and acknowledgement of the consequences for that right.","Uncaptured authorizations are canceled after decline or expiry. After capture, contact support promptly if the promised interaction was not delivered, was materially defective, duplicated, unauthorized, or unlawful. ReplyPass may refund, reverse creator earnings, or require evidence. Payment disputes may lead to temporary account restrictions while investigated."],bullets:["Personalized digital content and fully performed services may be subject to statutory exceptions to withdrawal rights, but only where legal conditions and required consents are met.","VIP cancellation stops future renewals; it does not automatically refund an already-started period unless law requires it or ReplyPass agrees."]},
        {title:"6. Content, safety and moderation",paragraphs:["You retain ownership of content you submit. You grant ReplyPass a worldwide, non-exclusive, royalty-free licence to host, process, transmit, resize, watermark, moderate and display it only as needed to operate, secure and promote the service according to your settings.","The Community Guidelines form part of these terms. We may remove content, restrict visibility, decline transactions, suspend accounts, preserve evidence, and report conduct where reasonably necessary for safety, legal compliance, fraud prevention, or enforcement. Users can report content and request review of a moderation decision by contacting us."]},
        {title:"7. Fees, payouts and taxes",paragraphs:["Prices include the disclosed ReplyPass platform fee. The current creator share is 85% and the ReplyPass platform fee is 15% of the relevant gross amount, before any allocation required for refunds, disputes, reversals, taxes, or provider adjustments. The checkout or creator dashboard controls if it displays a different lawful arrangement.","Creator earnings become payable only after successful capture and are paid to the creator’s Stripe balance. Bank payout timing is governed by Stripe settings, verification, reserves and applicable law. Creators are responsible for their taxes and business registrations."]},
        {title:"8. Availability and liability",paragraphs:["We provide the service with reasonable care but cannot guarantee uninterrupted availability, creator acceptance, bank timing, or that user content will meet personal expectations. To the maximum extent permitted by law, ReplyPass is not liable for indirect or unforeseeable loss. Nothing excludes liability that cannot lawfully be excluded, including liability for fraud, wilful misconduct, death or personal injury caused by negligence, or mandatory consumer rights."]},
        {title:"9. Changes, termination and law",paragraphs:["We may change these terms for legal, safety, or product reasons. Material changes will be notified in a reasonable manner before they take effect where required. Continued use after the effective date means acceptance where lawful.","These terms are governed by French law, without depriving an EEA consumer of mandatory protections in their country of residence. French courts have jurisdiction subject to mandatory consumer venue rights. Consumers should first contact ReplyPass; details of the appointed consumer mediator will be added before commercial launch."]},
      ]} />
  );
}
